<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DuLieuMauSeeder extends Seeder
{
    public function run(): void
    {
        // Production cleanup: user activity and community records are generated by real users.
    }
}
