/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
    ],
    darkMode: 'class',
    theme: {
        container: {
            center: true,
            padding: {
                DEFAULT: '1rem',
                sm: '1.5rem',
                lg: '1.5rem',
            },
        },
        extend: {
            fontFamily: {
                sans: ['"Be Vietnam Pro"', 'system-ui', 'sans-serif'],
                serif: ['Merriweather', 'Georgia', 'serif'],
                reading: ['Merriweather', 'Georgia', 'serif'],
            },
            fontSize: {
                h1: ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
                h2: ['24px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
                h3: ['20px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
                'body-ui': ['16px', { lineHeight: '1.5', letterSpacing: '0' }],
                'label-md': ['14px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '500' }],
                caption: ['12px', { lineHeight: '1.2', letterSpacing: '0' }],
                'reading-base': ['18px', { lineHeight: '1.8', letterSpacing: '0.01em' }],
            },
            colors: {
                library: {
                    background: '#FEF7FF',
                    surface: '#FFFFFF',
                    'surface-variant': '#F3EBF9',
                    'surface-elevated': '#EDE5F3',
                    'text-primary': '#1D1A24',
                    'text-secondary': '#4A4455',
                    'text-muted': '#7B7486',
                    primary: '#5300B7',
                    secondary: '#B4136D',
                    highlight: '#FD56A7',
                    border: '#EDE5F3',
                },
                primary: {
                    50: '#F3EBF9',
                    100: '#EDE5F3',
                    200: '#DCCBE9',
                    300: '#B997D8',
                    400: '#8E56CB',
                    500: '#6C16C1',
                    600: '#5300B7',
                    700: '#420092',
                    800: '#31006D',
                    900: '#210049',
                },
                secondary: {
                    50: '#FFF0F7',
                    100: '#FBD8EA',
                    200: '#F3AFD5',
                    300: '#E67DB9',
                    400: '#D94C9B',
                    500: '#C82A82',
                    600: '#B4136D',
                    700: '#8F0F56',
                    800: '#6B0B41',
                    900: '#47072B',
                },
                dark: {
                    bg: '#1D1A24',
                    surface: '#272230',
                    'surface-strong': '#322B3B',
                    border: '#4A4455',
                }
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '16px',
                lg: '24px',
                xl: '32px',
                '2xl': '48px',
                '3xl': '64px',
                gutter: '24px',
            },
            borderRadius: {
                sm: '0.25rem',
                DEFAULT: '0.5rem',
                md: '0.75rem',
                lg: '1rem',
                xl: '1.5rem',
                full: '9999px',
            },
            boxShadow: {
                card: '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
                overlay: '0 18px 44px -20px rgb(29 26 36 / 0.35)',
                premium: '0 4px 6px -1px rgb(0 0 0 / 0.05), 0 2px 4px -2px rgb(0 0 0 / 0.05)',
                'premium-hover': '0 16px 30px -18px rgb(29 26 36 / 0.45)',
            }
        },
    },
    plugins: [],
};
